# Generated by Django 3.0.10 on 2020-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201021_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('A', 'available'), ('B', 'busy'), ('U', 'unavailable')], default='A', max_length=1, verbose_name='status'),
        ),
    ]
