# Generated by Django 3.0.10 on 2020-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20201022_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description'),
        ),
    ]
